// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    var Slider, resStepValues;
    resStepValues = [0, 1e-5, 0.0001, 0.001, .01, .02, .03, .04, .05, 0.1, 1];
    Slider = (function() {

      function Slider(elem, text, callback) {
        this.slider = $(elem).slider({
          animate: true,
          min: 0,
          max: resStepValues.length - 1,
          value: 1,
          slide: function(event, ui) {
            var v;
            v = resStepValues[ui.value];
            $(text).val(v);
            return callback(v);
          }
        });
      }

      Slider.prototype.set_slider = function(v) {
        var set_i;
        set_i = 0;
        $.each(resStepValues, function(i, v2) {
          if (v2 <= v) {
            return set_i = i;
          }
        });
        return this.slider.slider("value", set_i);
      };

      return Slider;

    })();
    return window.Slider = Slider;
  });

}).call(this);
